//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalogRange
    {
        public int Id { get; set; }
        public Nullable<double> Lrv { get; set; }
        public Nullable<double> Urv { get; set; }
        public Nullable<double> AlramLow { get; set; }
        public Nullable<double> AlramHigh { get; set; }
        public Nullable<double> Span { get; set; }
    
        public virtual Instrument Instrument { get; set; }
    }
}
