//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InstrumentDBCONFContainer : DbContext
    {
        public InstrumentDBCONFContainer()
            : base("name=InstrumentDBCONFContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Instrument> InstrumentSet { get; set; }
        public virtual DbSet<SignalType> SignalTypeSet { get; set; }
        public virtual DbSet<Measurment_> Measurment { get; set; }
        public virtual DbSet<AnalogRange> AnalogRangeSet { get; set; }
    }
}
