//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        public int Instrument_Id { get; set; }
        public string InstrumentName { get; set; }
        public string SerialNo { get; set; }
        public string Comments { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual SignalType SignalType { get; set; }
        public virtual AnalogRange AnalogRange { get; set; }
        public virtual Measurment_ Measurment_ { get; set; }
    }
}
